CREATE TABLE userinfo (
name VARCHAR(50) NOT NULL,
addr VARCHAR(100) NOT NULL,
uname VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL,
pwd INT NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;